// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bots.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createBot = `-- name: CreateBot :one
INSERT INTO bots (id, bot_name, skills, owner_id, created_at, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, bot_name, skills, owner_id, created_at, updated_at
`

type CreateBotParams struct {
	ID        uuid.UUID `json:"id"`
	BotName   string    `json:"bot_name"`
	Skills    []int32   `json:"skills"`
	OwnerID   uuid.UUID `json:"owner_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) (Bot, error) {
	row := q.db.QueryRowContext(ctx, createBot,
		arg.ID,
		arg.BotName,
		pq.Array(arg.Skills),
		arg.OwnerID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.BotName,
		pq.Array(&i.Skills),
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBot = `-- name: DeleteBot :exec
DELETE FROM bots
WHERE id = $1
`

func (q *Queries) DeleteBot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBot, id)
	return err
}

const deleteUserTeam = `-- name: DeleteUserTeam :exec
DELETE FROM bots
WHERE owner_id = $1
`

func (q *Queries) DeleteUserTeam(ctx context.Context, ownerID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserTeam, ownerID)
	return err
}

const getBotbyID = `-- name: GetBotbyID :one
SELECT id, bot_name, skills, owner_id, created_at, updated_at FROM bots
WHERE id = $1
`

func (q *Queries) GetBotbyID(ctx context.Context, id uuid.UUID) (Bot, error) {
	row := q.db.QueryRowContext(ctx, getBotbyID, id)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.BotName,
		pq.Array(&i.Skills),
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNumBots = `-- name: GetNumBots :one
SELECT COUNT(*) FROM bots
`

func (q *Queries) GetNumBots(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNumBots)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserTeam = `-- name: GetUserTeam :many
SELECT id, bot_name, skills, owner_id, created_at, updated_at FROM bots
WHERE owner_id = $1
`

func (q *Queries) GetUserTeam(ctx context.Context, ownerID uuid.UUID) ([]Bot, error) {
	rows, err := q.db.QueryContext(ctx, getUserTeam, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bot
	for rows.Next() {
		var i Bot
		if err := rows.Scan(
			&i.ID,
			&i.BotName,
			pq.Array(&i.Skills),
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTeamNames = `-- name: GetUserTeamNames :many
SELECT bot_name FROM bots
WHERE owner_id = $1
`

func (q *Queries) GetUserTeamNames(ctx context.Context, ownerID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserTeamNames, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var bot_name string
		if err := rows.Scan(&bot_name); err != nil {
			return nil, err
		}
		items = append(items, bot_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetBots = `-- name: ResetBots :exec
DELETE FROM bots
`

func (q *Queries) ResetBots(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetBots)
	return err
}
